# Generated by Django 3.2.3 on 2021-05-27 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviereview',
            name='like',
        ),
    ]
